---
- hosts: all
  become: true
  tasks:
  # Add specified repository into sources list using specified filename.
  - apt_repository:
      repo: deb http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.2 main
      state: present
      filename: mongodb-org-3.2

  - name: Add an apt key by id from a keyserver
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: D68FA50FEA312927
      state: present

  - name: install mongodb package
    apt:
      name: mongodb-org
      update_cache: true

  - name: register mongodb service
    service: name=mongod enabled=yes

  - name: start mongodb service
    service: name=mongod state=started
